when we recorded team snext we need to valdiate team after match is finsided rite
we store playing 11 some where we get the playerss perfomace 

first we create api's
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/139186"

headers = {
	"x-rapidapi-key": "1f1c90995amsh68a46be32a51b17p125a5ejsn8e62c653206a",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
this getiing mathcid from this we get match id and team id
next from this we get squad
next we have
import requestsurl = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/139186/team/13"headers = {	"x-rapidapi-key": "1f1c90995amsh68a46be32a51b17p125a5ejsn8e62c653206a",	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"}response = requests.get(url, headers=headers)print(response.json())
playing 11
ok 
for t_key in [('t1_id', 't1_name'), ('t2_id', 't2_name')]:
            t_name = match_details[t_key[1]]

            squad_url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{match_details['id']}/team/{t_id}"
            s_res = requests.get(squad_url, headers=HEADERS)
            s_data = s_res.json()

            final_output += f"\n--- {t_name} Squad ---\n"
            for group in s_data.get('player', []):
                if group.get('category') == "playing XI":
                    for p in group.get('player', []):
                        final_output += f"- {p.get('name')} ({p.get('role')}) [ID: {p.get('id')}]\n"

        cache.set(cache_key, final_output)
        return final_output
liek this cleaere

next we have
from that playing 11 we get perfomace both batting andbowling perfomances
ok

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/139186/scard"headers = {	"x-rapidapi-key": "1f1c90995amsh68a46be32a51b17p125a5ejsn8e62c653206a",	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"}response = requests.get(url, headers=headers)print(response.json())
from this we get and 
{
  "scorecard": [
    {
      "inningsid": 1,
      "batsman": [
        {
          "id": 9443,
          "balls": 9,
          "runs": 13,
          "fours": 1,
          "sixes": 1,
          "strkrate": "144.44",
          "name": "Tim Seifert",
          "nickname": "Tim Seifert",
          "iscaptain": false,
          "iskeeper": true,
          "outdec": "c Quinton de Kock b Marco Jansen",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 11172,
          "balls": 17,
          "runs": 31,
          "fours": 4,
          "sixes": 2,
          "strkrate": "182.35",
          "name": "Finn Allen",
          "nickname": "Finn Allen",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "c Aiden Markram b Marco Jansen",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 11177,
          "balls": 8,
          "runs": 13,
          "fours": 1,
          "sixes": 1,
          "strkrate": "162.5",
          "name": "Rachin Ravindra",
          "nickname": "Rachin Ravindra",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "c David Miller b Marco Jansen",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 10693,
          "balls": 3,
          "runs": 1,
          "fours": 0,
          "sixes": 0,
          "strkrate": "33.33",
          "name": "Glenn Phillips",
          "nickname": "Glenn Phillips",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "b Keshav Maharaj",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 9976,
          "balls": 26,
          "runs": 48,
          "fours": 6,
          "sixes": 2,
          "strkrate": "184.62",
          "name": "Mark Chapman",
          "nickname": "Mark Chapman",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "c Ryan Rickelton b Marco Jansen",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 10713,
          "balls": 24,
          "runs": 32,
          "fours": 2,
          "sixes": 1,
          "strkrate": "133.33",
          "name": "Daryl Mitchell",
          "nickname": "Daryl Mitchell",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "c Tristan Stubbs b Lungi Ngidi",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 10100,
          "balls": 10,
          "runs": 4,
          "fours": 0,
          "sixes": 0,
          "strkrate": "40",
          "name": "Mitchell Santner",
          "nickname": "Mitchell Santner",
          "iscaptain": true,
          "iskeeper": false,
          "outdec": "c Ryan Rickelton b Corbin Bosch",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 8983,
          "balls": 15,
          "runs": 23,
          "fours": 3,
          "sixes": 0,
          "strkrate": "153.33",
          "name": "James Neesham",
          "nickname": "James Neesham",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "not out",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 9067,
          "balls": 8,
          "runs": 9,
          "fours": 1,
          "sixes": 0,
          "strkrate": "112.5",
          "name": "Matt Henry",
          "nickname": "Matt Henry",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "not out",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 10692,
          "balls": 0,
          "runs": 0,
          "fours": 0,
          "sixes": 0,
          "strkrate": "0",
          "name": "Lockie Ferguson",
          "nickname": "Lockie Ferguson",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 8554,
          "balls": 0,
          "runs": 0,
          "fours": 0,
          "sixes": 0,
          "strkrate": "0",
          "name": "Jacob Duffy",
          "nickname": "Jacob Duffy",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        }
      ],
      "bowler": [
        {
          "id": 9603,
          "overs": "4",
          "maidens": 0,
          "wickets": 1,
          "runs": 34,
          "economy": "8.5",
          "name": "Lungi Ngidi",
          "nickname": "Lungi Ngidi",
          "iscaptain": false,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 24,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 9585,
          "overs": "4",
          "maidens": 0,
          "wickets": 0,
          "runs": 27,
          "economy": "6.8",
          "name": "Kagiso Rabada",
          "nickname": "Kagiso Rabada",
          "iscaptain": false,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 24,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 14565,
          "overs": "4",
          "maidens": 0,
          "wickets": 4,
          "runs": 40,
          "economy": "10",
          "name": "Marco Jansen",
          "nickname": "Marco Jansen",
          "iscaptain": false,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 24,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 9720,
          "overs": "3",
          "maidens": 0,
          "wickets": 1,
          "runs": 24,
          "economy": "8",
          "name": "Keshav Maharaj",
          "nickname": "Keshav Maharaj",
          "iscaptain": false,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 18,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 9576,
          "overs": "4",
          "maidens": 0,
          "wickets": 1,
          "runs": 34,
          "economy": "8.5",
          "name": "Corbin Bosch",
          "nickname": "Corbin Bosch",
          "iscaptain": false,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 24,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": "IN"
        },
        {
          "id": 9582,
          "overs": "1",
          "maidens": 0,
          "wickets": 0,
          "runs": 15,
          "economy": "15",
          "name": "Aiden Markram",
          "nickname": "Aiden Markram",
          "iscaptain": true,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 6,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        }
      ],
      "fow": {
        "fow": [
          {
            "batsmanid": 9443,
            "batsmanname": "Tim Seifert",
            "overnbr": 3.2,
            "runs": 33,
            "ballnbr": 20
          },
          {
            "batsmanid": 11177,
            "batsmanname": "Rachin Ravindra",
            "overnbr": 5.2,
            "runs": 57,
            "ballnbr": 32
          },
          {
            "batsmanid": 11172,
            "batsmanname": "Finn Allen",
            "overnbr": 5.5,
            "runs": 58,
            "ballnbr": 35
          },
          {
            "batsmanid": 10693,
            "batsmanname": "Glenn Phillips",
            "overnbr": 6.4,
            "runs": 64,
            "ballnbr": 40
          },
          {
            "batsmanid": 9976,
            "batsmanname": "Mark Chapman",
            "overnbr": 13.6,
            "runs": 138,
            "ballnbr": 84
          },
          {
            "batsmanid": 10713,
            "batsmanname": "Daryl Mitchell",
            "overnbr": 15.3,
            "runs": 141,
            "ballnbr": 93
          },
          {
            "batsmanid": 10100,
            "batsmanname": "Mitchell Santner",
            "overnbr": 16.4,
            "runs": 145,
            "ballnbr": 100
          }
        ]
      },
      "extras": {
        "legbyes": 1,
        "byes": 0,
        "wides": 0,
        "noballs": 0,
        "penalty": 0,
        "total": 1
      },
      "pp": {
        "powerplay": [
          {
            "id": 27,
            "ovrfrom": 0.1,
            "ovrto": 6,
            "pptype": "Mandatory",
            "run": 58,
            "wickets": 0
          }
        ]
      },
      "score": 175,
      "wickets": 7,
      "overs": 20,
      "runrate": 8.75,
      "batteamname": "New Zealand",
      "batteamsname": "NZ",
      "isdeclared": false,
      "isfollowon": false,
      "ballnbr": 120,
      "rpb": 1.46,
      "partnership": {
        "partnership": [
          {
            "id": 0,
            "bat1id": 9443,
            "bat1name": "Tim Seifert",
            "bat1runs": 13,
            "bat1fours": 1,
            "bat1sixes": 1,
            "bat2id": 11172,
            "bat2name": "Finn Allen",
            "bat2runs": 20,
            "bat2fours": 3,
            "bat2sixes": 1,
            "totalruns": 33,
            "totalballs": 20,
            "bat1balls": 9,
            "bat2balls": 11,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 3,
            "bat1twos": 0,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 1,
            "bat1sixers": 1,
            "bat2ones": 2,
            "bat2twos": 0,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 3,
            "bat2sixers": 1
          },
          {
            "id": 0,
            "bat1id": 11177,
            "bat1name": "Rachin Ravindra",
            "bat1runs": 13,
            "bat1fours": 1,
            "bat1sixes": 1,
            "bat2id": 11172,
            "bat2name": "Finn Allen",
            "bat2runs": 11,
            "bat2fours": 1,
            "bat2sixes": 1,
            "totalruns": 24,
            "totalballs": 12,
            "bat1balls": 8,
            "bat2balls": 4,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 3,
            "bat1twos": 0,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 1,
            "bat1sixers": 1,
            "bat2ones": 1,
            "bat2twos": 0,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 1,
            "bat2sixers": 1
          },
          {
            "id": 0,
            "bat1id": 10693,
            "bat1name": "Glenn Phillips",
            "bat1runs": 0,
            "bat1fours": 0,
            "bat1sixes": 0,
            "bat2id": 11172,
            "bat2name": "Finn Allen",
            "bat2runs": 0,
            "bat2fours": 0,
            "bat2sixes": 0,
            "totalruns": 1,
            "totalballs": 3,
            "bat1balls": 1,
            "bat2balls": 2,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 0,
            "bat1twos": 0,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 0,
            "bat1sixers": 0,
            "bat2ones": 0,
            "bat2twos": 0,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 0,
            "bat2sixers": 0
          },
          {
            "id": 0,
            "bat1id": 10693,
            "bat1name": "Glenn Phillips",
            "bat1runs": 1,
            "bat1fours": 0,
            "bat1sixes": 0,
            "bat2id": 9976,
            "bat2name": "Mark Chapman",
            "bat2runs": 5,
            "bat2fours": 1,
            "bat2sixes": 0,
            "totalruns": 6,
            "totalballs": 5,
            "bat1balls": 2,
            "bat2balls": 3,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 1,
            "bat1twos": 0,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 0,
            "bat1sixers": 0,
            "bat2ones": 1,
            "bat2twos": 0,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 1,
            "bat2sixers": 0
          },
          {
            "id": 0,
            "bat1id": 10713,
            "bat1name": "Daryl Mitchell",
            "bat1runs": 31,
            "bat1fours": 2,
            "bat1sixes": 1,
            "bat2id": 9976,
            "bat2name": "Mark Chapman",
            "bat2runs": 43,
            "bat2fours": 5,
            "bat2sixes": 2,
            "totalruns": 74,
            "totalballs": 44,
            "bat1balls": 21,
            "bat2balls": 23,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 9,
            "bat1twos": 4,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 2,
            "bat1sixers": 1,
            "bat2ones": 9,
            "bat2twos": 1,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 5,
            "bat2sixers": 2
          },
          {
            "id": 0,
            "bat1id": 10713,
            "bat1name": "Daryl Mitchell",
            "bat1runs": 1,
            "bat1fours": 0,
            "bat1sixes": 0,
            "bat2id": 10100,
            "bat2name": "Mitchell Santner",
            "bat2runs": 2,
            "bat2fours": 0,
            "bat2sixes": 0,
            "totalruns": 3,
            "totalballs": 9,
            "bat1balls": 3,
            "bat2balls": 6,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 1,
            "bat1twos": 0,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 0,
            "bat1sixers": 0,
            "bat2ones": 2,
            "bat2twos": 0,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 0,
            "bat2sixers": 0
          },
          {
            "id": 0,
            "bat1id": 8983,
            "bat1name": "James Neesham",
            "bat1runs": 2,
            "bat1fours": 0,
            "bat1sixes": 0,
            "bat2id": 10100,
            "bat2name": "Mitchell Santner",
            "bat2runs": 2,
            "bat2fours": 0,
            "bat2sixes": 0,
            "totalruns": 4,
            "totalballs": 7,
            "bat1balls": 3,
            "bat2balls": 4,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 2,
            "bat1twos": 0,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 0,
            "bat1sixers": 0,
            "bat2ones": 2,
            "bat2twos": 0,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 0,
            "bat2sixers": 0
          },
          {
            "id": 0,
            "bat1id": 8983,
            "bat1name": "James Neesham",
            "bat1runs": 21,
            "bat1fours": 3,
            "bat1sixes": 0,
            "bat2id": 9067,
            "bat2name": "Matt Henry",
            "bat2runs": 9,
            "bat2fours": 1,
            "bat2sixes": 0,
            "totalruns": 30,
            "totalballs": 20,
            "bat1balls": 12,
            "bat2balls": 8,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 5,
            "bat1twos": 2,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 3,
            "bat1sixers": 0,
            "bat2ones": 5,
            "bat2twos": 0,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 1,
            "bat2sixers": 0
          }
        ]
      }
    },
    {
      "inningsid": 2,
      "batsman": [
        {
          "id": 9582,
          "balls": 44,
          "runs": 86,
          "fours": 8,
          "sixes": 4,
          "strkrate": "195.45",
          "name": "Aiden Markram",
          "nickname": "Aiden Markram",
          "iscaptain": true,
          "iskeeper": false,
          "outdec": "not out",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 8520,
          "balls": 14,
          "runs": 20,
          "fours": 3,
          "sixes": 1,
          "strkrate": "142.86",
          "name": "Quinton de Kock",
          "nickname": "Quinton de Kock",
          "iscaptain": false,
          "iskeeper": true,
          "outdec": "b Lockie Ferguson",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 13070,
          "balls": 11,
          "runs": 21,
          "fours": 2,
          "sixes": 1,
          "strkrate": "190.91",
          "name": "Ryan Rickelton",
          "nickname": "Ryan Rickelton",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "c Daryl Mitchell b James Neesham",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 20538,
          "balls": 17,
          "runs": 21,
          "fours": 1,
          "sixes": 1,
          "strkrate": "123.53",
          "name": "Dewald Brevis",
          "nickname": "Dewald Brevis",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "c Daryl Mitchell b Rachin Ravindra",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 6349,
          "balls": 17,
          "runs": 24,
          "fours": 1,
          "sixes": 1,
          "strkrate": "141.18",
          "name": "David Miller",
          "nickname": "David Miller",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "not out",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 19243,
          "balls": 0,
          "runs": 0,
          "fours": 0,
          "sixes": 0,
          "strkrate": "0",
          "name": "Tristan Stubbs",
          "nickname": "Tristan Stubbs",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 14565,
          "balls": 0,
          "runs": 0,
          "fours": 0,
          "sixes": 0,
          "strkrate": "0",
          "name": "Marco Jansen",
          "nickname": "Marco Jansen",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 9576,
          "balls": 0,
          "runs": 0,
          "fours": 0,
          "sixes": 0,
          "strkrate": "0",
          "name": "Corbin Bosch",
          "nickname": "Corbin Bosch",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": "IN"
        },
        {
          "id": 9585,
          "balls": 0,
          "runs": 0,
          "fours": 0,
          "sixes": 0,
          "strkrate": "0",
          "name": "Kagiso Rabada",
          "nickname": "Kagiso Rabada",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 9720,
          "balls": 0,
          "runs": 0,
          "fours": 0,
          "sixes": 0,
          "strkrate": "0",
          "name": "Keshav Maharaj",
          "nickname": "Keshav Maharaj",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 9603,
          "balls": 0,
          "runs": 0,
          "fours": 0,
          "sixes": 0,
          "strkrate": "0",
          "name": "Lungi Ngidi",
          "nickname": "Lungi Ngidi",
          "iscaptain": false,
          "iskeeper": false,
          "outdec": "",
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "iscbplusfree": false,
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        }
      ],
      "bowler": [
        {
          "id": 9067,
          "overs": "4",
          "maidens": 0,
          "wickets": 0,
          "runs": 38,
          "economy": "9.5",
          "name": "Matt Henry",
          "nickname": "Matt Henry",
          "iscaptain": false,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 24,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 10692,
          "overs": "3.1",
          "maidens": 0,
          "wickets": 1,
          "runs": 33,
          "economy": "10.4",
          "name": "Lockie Ferguson",
          "nickname": "Lockie Ferguson",
          "iscaptain": false,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 19,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 8554,
          "overs": "3",
          "maidens": 0,
          "wickets": 0,
          "runs": 50,
          "economy": "16.7",
          "name": "Jacob Duffy",
          "nickname": "Jacob Duffy",
          "iscaptain": false,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 18,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 10100,
          "overs": "4",
          "maidens": 0,
          "wickets": 0,
          "runs": 33,
          "economy": "8.2",
          "name": "Mitchell Santner",
          "nickname": "Mitchell Santner",
          "iscaptain": true,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 24,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 8983,
          "overs": "2",
          "maidens": 0,
          "wickets": 1,
          "runs": 15,
          "economy": "7.5",
          "name": "James Neesham",
          "nickname": "James Neesham",
          "iscaptain": false,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 12,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        },
        {
          "id": 11177,
          "overs": "1",
          "maidens": 0,
          "wickets": 1,
          "runs": 9,
          "economy": "9",
          "name": "Rachin Ravindra",
          "nickname": "Rachin Ravindra",
          "iscaptain": false,
          "iskeeper": false,
          "videotype": "",
          "videourl": "",
          "videoid": 0,
          "dots": 0,
          "balls": 6,
          "rpb": 0,
          "planid": 0,
          "imageid": 0,
          "premiumvideourl": "",
          "ispremiumfree": false,
          "inmatchchange": "",
          "isoverseas": false,
          "playingxichange": ""
        }
      ],
      "fow": {
        "fow": [
          {
            "batsmanid": 8520,
            "batsmanname": "Quinton de Kock",
            "overnbr": 4.4,
            "runs": 62,
            "ballnbr": 28
          },
          {
            "batsmanid": 13070,
            "batsmanname": "Ryan Rickelton",
            "overnbr": 7.4,
            "runs": 102,
            "ballnbr": 46
          },
          {
            "batsmanid": 20538,
            "batsmanname": "Dewald Brevis",
            "overnbr": 11.4,
            "runs": 131,
            "ballnbr": 70
          }
        ]
      },
      "extras": {
        "legbyes": 0,
        "byes": 0,
        "wides": 6,
        "noballs": 0,
        "penalty": 0,
        "total": 6
      },
      "pp": {
        "powerplay": [
          {
            "id": 28,
            "ovrfrom": 0.1,
            "ovrto": 6,
            "pptype": "Mandatory",
            "run": 83,
            "wickets": 0
          }
        ]
      },
      "score": 178,
      "wickets": 3,
      "overs": 17.1,
      "runrate": 10.37,
      "batteamname": "South Africa",
      "batteamsname": "RSA",
      "isdeclared": false,
      "isfollowon": false,
      "ballnbr": 103,
      "rpb": 1.73,
      "partnership": {
        "partnership": [
          {
            "id": 0,
            "bat1id": 9582,
            "bat1name": "Aiden Markram",
            "bat1runs": 41,
            "bat1fours": 5,
            "bat1sixes": 3,
            "bat2id": 8520,
            "bat2name": "Quinton de Kock",
            "bat2runs": 20,
            "bat2fours": 3,
            "bat2sixes": 1,
            "totalruns": 62,
            "totalballs": 28,
            "bat1balls": 14,
            "bat2balls": 14,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 3,
            "bat1twos": 0,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 5,
            "bat1sixers": 3,
            "bat2ones": 2,
            "bat2twos": 0,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 3,
            "bat2sixers": 1
          },
          {
            "id": 0,
            "bat1id": 9582,
            "bat1name": "Aiden Markram",
            "bat1runs": 18,
            "bat1fours": 2,
            "bat1sixes": 1,
            "bat2id": 13070,
            "bat2name": "Ryan Rickelton",
            "bat2runs": 21,
            "bat2fours": 2,
            "bat2sixes": 1,
            "totalruns": 40,
            "totalballs": 18,
            "bat1balls": 7,
            "bat2balls": 11,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 2,
            "bat1twos": 1,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 2,
            "bat1sixers": 1,
            "bat2ones": 5,
            "bat2twos": 1,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 2,
            "bat2sixers": 1
          },
          {
            "id": 0,
            "bat1id": 9582,
            "bat1name": "Aiden Markram",
            "bat1runs": 7,
            "bat1fours": 0,
            "bat1sixes": 0,
            "bat2id": 20538,
            "bat2name": "Dewald Brevis",
            "bat2runs": 21,
            "bat2fours": 1,
            "bat2sixes": 1,
            "totalruns": 29,
            "totalballs": 24,
            "bat1balls": 7,
            "bat2balls": 17,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 7,
            "bat1twos": 0,
            "bat1threes": 0,
            "bat1fives": 0,
            "bat1boundaries": 0,
            "bat1sixers": 0,
            "bat2ones": 5,
            "bat2twos": 3,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 1,
            "bat2sixers": 1
          },
          {
            "id": 0,
            "bat1id": 9582,
            "bat1name": "Aiden Markram",
            "bat1runs": 20,
            "bat1fours": 1,
            "bat1sixes": 0,
            "bat2id": 6349,
            "bat2name": "David Miller",
            "bat2runs": 24,
            "bat2fours": 1,
            "bat2sixes": 1,
            "totalruns": 47,
            "totalballs": 33,
            "bat1balls": 16,
            "bat2balls": 17,
            "teamname": "",
            "teamid": 0,
            "bat1ones": 9,
            "bat1twos": 1,
            "bat1threes": 0,
            "bat1fives": 1,
            "bat1boundaries": 1,
            "bat1sixers": 0,
            "bat2ones": 12,
            "bat2twos": 1,
            "bat2threes": 0,
            "bat2fives": 0,
            "bat2boundaries": 1,
            "bat2sixers": 1
          }
        ]
      }
    }
  ],
  "ismatchcomplete": true,
  "appindex": {
    "seotitle": "Cricket scorecard - NZ vs RSA 24th Match, Group D,ICC Men's T20 World Cup 2026 | Cricbuzz.com",
    "weburl": "http://www.cricbuzz.com/live-cricket-scorecard/139186/nz-vs-rsa-24th-match-group-d-icc-mens-t20-world-cup-2026"
  },
  "status": "South Africa won by 7 wkts",
  "responselastupdated": 1771581170
}
we have this for get get all players batting and bowling so give everytin in orer in seprate fucntion clelrer 
we pass jsut match id pelase clerer simple